"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app --use-pythonpath -A
    (non-alias mode does not work)
"""
from setuptools import setup, find_packages
import os, sys
sys.path.insert(0, os.path.abspath('../python'))

IS_ALIASMODE = ('-A' in sys.argv)

APP = ['../python/piscope_noargv.py']
OPTIONS = {'argv_emulation': False,
           'includes':[],
           'packages':[],
 'iconfile': '../python/ifigure/resources/icon/app_logo.icns',
 'plist':{'NSHumanReadableCopyright': '2012-2016 S.Shiraiwa',
	  'CFBundleName':'piScope',}
#	  'LSUIElement':1}           
}
PACKAGES=find_packages('../python')

setup(
    app=APP,
    version='beta', 
    author='S. Shiraiwa',
    data_files=[],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    package_dir={'ifigure':'../python/ifigure'},
    zip_safe = False,
)

import shutil

if not IS_ALIASMODE:
   print 'Copying ifigure package'
   src = '../python/ifigure'
   dst = './dist/piscope.app/Contents/Resources/lib/python2.7/ifigure'
   shutil.copytree(src, dst)

   lsrc = './app_template/launch_piscope_standalone.app'
   ldst = './Launch piScope (Py2App).app'

   import py2app
   bbbb = os.path.dirname(os.path.dirname(py2app.__path__[0]))
   site_src = os.path.join(bbbb, 'py2app', 'apptemplate', 'lib', 'site.py')
   site_dst1 = './dist/piscope.app/Contents/Resources/site.py'
   shutil.copyfile(site_src, site_dst1)

else:
   lsrc = 'app_template/launch_piscope_aliasmode.app'
   ldst = './Launch piScope (Py2App).app'

if os.path.exists(ldst):
    shutil.rmtree(ldst)
shutil.copytree(lsrc, ldst)

