"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup, find_packages
import os, sys


sys.path.insert(0, os.path.abspath('../python'))

IS_ALIASMODE = ('-A' in sys.argv)

APP = ['./distribute_setup.py']
OPTIONS = {'argv_emulation': True,
           'includes':[],#'hgapi', 'pip'], #['hgapi'],
           'packages':[], ###numpy', 'wx'], 
 'plist':{'NSHumanReadableCopyright': '2012-2014 S.Shiraiwa'}}
PACKAGES=find_packages('../python')

#datadir = '../python/ifigure/resources'
#DATA_FILES = [('/'.join(root.split('/')[3:]), [os.path.join(root, f) for f in files])
#    for root, dirs, files in os.walk(datadir)]
#DATA_FILES = [('resources',['../python/ifigure/resources/icon/app_logo_small.png']),]

setup(
    app=APP,
    version='beta', 
    author='S. Shiraiwa',
    data_files=[],
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
#    packages = PACKAGES,
#    packages = ['ifigure', 'ifigure.add_on'],
    package_dir={'ifigure':'../python/ifigure'},
    zip_safe = False,
)




